version: '3'

services:
  server:
    container_name: agricoladb-server
    build:
      context: .
      dockerfile: ./docker/local/server/Dockerfile
    ports:
      - 8080:8080
    volumes:       
      - ./src:/go/src/agricoladb-server
