version: '3'

services:
  server:
    container_name: agricoladb-server
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - 8080:8080
    volumes:       
      - ./:/go/src/agricoladb-server
    depends_on:
      - db
  db:
    container_name: agricoladb-db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      MYSQL_DATABASE: agricoladb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
