name: build-containers

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - name: build
        uses: docker/build-push-action@v4
        with:
          push: false
          context: .
          file: ./docker/production/server/Dockerfile
          tags: agricoladb-server:v0.1.0-alpha
          cache-to: type=gha,mode=max
