name: build-containers

on:
  workflow_call:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8
      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: ./docker/production/server/Dockerfile
          tags: ghcr.io/agricoladevjp/agricoladb-server/server:v0.0.2-alpha
          cache-to: type=gha,mode=max
