name: ci-ent

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "ent/*"
jobs:
  ent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: ent/contrib/ci@master
