name: ci-feature

on:
  pull_request:

jobs:
  judge-execute:
    outputs:
      needs-test-go: ${{ steps.needs-test-go.outputs.any_changed }}
      needs-test-ent: ${{ steps.needs-test-ent.outputs.any_changed }}
      needs-test-actions: ${{ steps.needs-test-actions.outputs.any_changed }}
      needs-test-integration: "true"
      needs-test-terraform: ${{ steps.needs-test-terraform.outputs.any_changed }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: needs-test-go
        uses: tj-actions/changed-files@v35
        with:
          files: |
            .github/workflows/test-go.yml
            **/*.go
            go.mod
            go.sum
            initdb/masterdata/*.csv
      - id: needs-test-ent
        uses: tj-actions/changed-files@v35
        with:
          files: |
            .github/workflows/test-ent.yml
            ent/**/*
            go.mod
            go.sum
      - id: needs-test-actions
        uses: tj-actions/changed-files@v35
        with:
          files: |
            .github/workflows/*.yml
            .github/actionlint-matcher.json
      - id: needs-test-terraform
        uses: tj-actions/changed-files@v35
        with:
          files: |
            terraform/**/*

  test-go:
    needs: judge-execute
    if: needs.judge-execute.outputs.needs-test-go == 'true'
    uses: ./.github/workflows/test-go.yml

  test-ent:
    needs: judge-execute
    if: needs.judge-execute.outputs.needs-test-ent == 'true'
    uses: ./.github/workflows/test-ent.yml

  test-actions:
    needs: judge-execute
    if: needs.judge-execute.outputs.needs-test-actions == 'true'
    uses: ./.github/workflows/test-actions.yml

  test-integration:
    needs: judge-execute
    if: needs.judge-execute.outputs.needs-test-integration == 'true'
    uses: ./.github/workflows/test-integration.yml

  test-terraform:
    needs: judge-execute
    if: needs.judge-execute.outputs.needs-test-terraform == 'true'
    uses: ./.github/workflows/test-terraform.yml

  deploy-lambda:
    uses: ./.github/workflows/deploy-lambda.yml
