name: ci-integration

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Docker build
        run: make docker-build-test
      - name: Docker start
        run: make docker-start-test
      - name: Docker stop
        run: make docker-stop-test
