name: ci-integration

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Docker build
        run: make docker-build-test
      - name: Docker start
        run: make docker-start-test
      - name: Install runn
        run: go install github.com/k1LoW/runn/cmd/runn@latest
      - name: E2E test
        run: runn run ./e2e/**/*.yml
      - name: Docker stop
        run: make docker-stop-test
