name: ci-main

on:
  push:
    branches:
      - main

jobs:
  test-go:
    uses: ./.github/workflows/test-go.yml

  test-ent:
    uses: ./.github/workflows/test-ent.yml

  test-actions:
    uses: ./.github/workflows/test-actions.yml

  test-integration:
    uses: ./.github/workflows/test-integration.yml

  test-terraform:
    uses: ./.github/workflows/test-terraform.yml

  build-containers:
    needs:
      - test-go
      - test-ent
      - test-integration
    uses: ./.github/workflows/build-containers.yml
    with:
      needs-push: true

  build-binaries:
    needs:
      - test-go
      - test-ent
      - test-integration
    uses: ./.github/workflows/build-binaries.yml
