name: ci-release

on:
  push:
    tags:
      - "v*"

jobs:
  test-go:
    uses: ./.github/workflows/test-go.yml

  test-ent:
    uses: ./.github/workflows/test-ent.yml

  test-actions:
    uses: ./.github/workflows/test-actions.yml

  test-integration:
    uses: ./.github/workflows/test-integration.yml

  build-containers:
    needs:
      - test-go
      - test-ent
      - test-actions
      - test-integration
    uses: ./.github/workflows/build-containers.yml
    with:
      needs-push: true

  build-release-binaries:
    needs:
      - test-go
      - test-ent
      - test-actions
      - test-integration
    uses: ./.github/workflows/build-release-binaries.yml

  deploy:
    uses: ./.github/workflows/deploy.yml
