name: on pull request

on:
  pull_request:

jobs:
  judge-execute:
    outputs:
      needs-test-go: ${{ steps.needs-test-go.outputs.any_changed }}
      needs-test-ent: ${{ steps.needs-test-ent.outputs.any_changed }}
      needs-test-actions: ${{ steps.needs-test-actions.outputs.any_changed }}
      needs-test-integration: "true"
      needs-test-terraform: ${{ steps.needs-test-terraform.outputs.any_changed }}
      needs-test-docker: ${{ steps.needs-test-docker.outputs.any_changed }}
      needs-generate-go: ${{ steps.metadata.outputs.dependency-names == 'entgo.io/ent' || steps.metadata.outputs.dependency-names == 'github.com/99designs/gqlgen' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: needs-test-go
        uses: tj-actions/changed-files@v42
        with:
          files: |
            .github/workflows/wf-test-go.yml
            **/*.go
            go.mod
            go.sum
            initdb/masterdata/*.csv
      - id: needs-test-ent
        uses: tj-actions/changed-files@v42
        with:
          files: |
            .github/workflows/wf-test-ent.yml
            ent/**/*
            go.mod
            go.sum
            gqlgen.yml
      - id: needs-test-actions
        uses: tj-actions/changed-files@v42
        with:
          files: |
            .github/workflows/*.yml
            .github/actionlint-matcher.json
      - id: needs-test-terraform
        uses: tj-actions/changed-files@v42
        with:
          files: |
            terraform/**/*
      - id: needs-test-docker
        uses: tj-actions/changed-files@v42
        with:
          files: |
            .github/workflows/wf-build-containers.yml
            **/*.go
            go.mod
            go.sum
            initdb/masterdata/*.csv
            docker/production/server/Dockerfile
      - name: Dependabot metadata
        id: metadata
        if: github.actor == 'dependabot[bot]'
        uses: dependabot/fetch-metadata@v1

  test-go:
    needs: judge-execute
    if: needs.judge-execute.outputs.needs-test-go == 'true'
    uses: ./.github/workflows/wf-test-go.yml

  test-ent:
    needs: judge-execute
    if: needs.judge-execute.outputs.needs-test-ent == 'true'
    uses: ./.github/workflows/wf-test-ent.yml

  test-actions:
    needs: judge-execute
    if: needs.judge-execute.outputs.needs-test-actions == 'true'
    uses: ./.github/workflows/wf-test-actions.yml

  test-integration:
    needs: judge-execute
    if: needs.judge-execute.outputs.needs-test-integration == 'true'
    uses: ./.github/workflows/wf-test-integration.yml

  test-terraform:
    needs: judge-execute
    if: needs.judge-execute.outputs.needs-test-terraform == 'true'
    uses: ./.github/workflows/wf-test-terraform.yml

  test-docker:
    needs: judge-execute
    if: needs.judge-execute.outputs.needs-test-docker == 'true'
    uses: ./.github/workflows/wf-build-containers.yml
    with:
      needs-push: false

  generate-go:
    needs: judge-execute
    if: needs.judge-execute.outputs.needs-generate-go == 'true'
    uses: ./.github/workflows/wf-generate-go.yml
