name: on release

on:
  push:
    tags:
      - "v*"

jobs:
  test-go:
    uses: ./.github/workflows/wf-test-go.yml

  test-ent:
    uses: ./.github/workflows/wf-test-ent.yml

  test-actions:
    uses: ./.github/workflows/wf-test-actions.yml

  test-integration:
    uses: ./.github/workflows/wf-test-integration.yml

  build-containers:
    needs:
      - test-go
      - test-ent
      - test-actions
      - test-integration
    uses: ./.github/workflows/wf-build-containers.yml
    with:
      needs-push: true

  build-release-binaries:
    needs:
      - test-go
      - test-ent
      - test-actions
      - test-integration
    uses: ./.github/workflows/wf-build-release-binaries.yml
  
  dispatch-deploy:
    needs:
      - build-containers
      - build-release-binaries
    uses: ./.github/workflows/wf-dispatch-deploy.yml
    secrets: inherit
  