name: test-integration

on:
  workflow_call:

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: docker build
        run: make docker-build-test
      - name: docker start
        run: make docker-start-test
      - name: install runn
        run: go install github.com/k1LoW/runn/cmd/runn@latest
      - name: e2e test
        run: runn run ./e2e/**/*.yml
      - name: docker stop
        run: make docker-stop-test
