name: test-go

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: src/go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
