name: test-integration

on:
  workflow_call:

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mariadb:10.10
        ports:
          - 3306:3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: agricoladb
          MYSQL_ROOT_PASSWORD: passw0rd
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: install runn
        run: go install github.com/k1LoW/runn/cmd/runn@latest
      - name: execute migration
        run: DB_USER=user DB_PASSWORD=password go run cmd/migration/main.go
      - name: e2e test
        run: runn run ./e2e/**/*.yml
