name: test-actions

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: add problem matcher
        run: echo "::add-matcher::.github/actionlint-matcher.json"
      - name: run actonlint
        run: ./actionlint
        shell: bash
