name: test-ent

on:
  workflow_call:

jobs:
  codegen-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: src/go.mod
          cache-dependency-path: src/go.sum
      - uses: ent/contrib/ci@master
