name: build-containers

on:
  workflow_call:
    inputs:
      needs-push:
        required: true
        type: boolean

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta-server
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/agricoladevjp/agricoladb-server/server
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      - name: build server image
        uses: docker/build-push-action@v5
        with:
          push: ${{ inputs.needs-push }}
          context: .
          file: ./docker/production/server/Dockerfile
          tags: ${{ steps.meta-server.outputs.tags }}
          labels: ${{ steps.meta-server.outputs.labels }}
          cache-to: type=gha,mode=max
