name: generate-go

on:
  workflow_call:

permissions:
  contents: read

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 792029
          private-key: ${{ secrets.AGRICOLADEVJP_BOT_PRIVATE_KEY }}
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: Generate codes
        run: go generate ./...
      - name: Check changes
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true
      - name: Commit changes
        if: steps.diff.outcome == 'failure'
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit --author=. -m 'go generate'
      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        if: steps.diff.outcome == 'failure'
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          branch: ${{ github.ref }}
