name: test-terraform

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4
      - name: terraform version
        run: echo "TF_VERSION=$(cat .terraform-version)" >> "$GITHUB_ENV"
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::131551699606:role/agricoladb-server-github-actions-role
          aws-region: ap-northeast-1
      - name: terraform init
        run: terraform init -lockfile=readonly
      - name: terraform validate
        run: terraform validate
      - name: terraform plan
        run: terraform plan -input=false

  format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4
      - name: terraform version
        run: echo "TF_VERSION=$(cat .terraform-version)" >> "$GITHUB_ENV"
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: terraform format
        run: terraform fmt -check
