name: test-ent

on:
  workflow_call:

jobs:
  codegen-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 1.22
      - uses: ent/contrib/ci@master
